// Shared Devicon mapping dictionary
export const techMap: Record<string, string> = {
  // Frontend Frameworks & Libraries
  react: "devicon-react-original colored",
  reactjs: "devicon-react-original colored",
  nextjs: "devicon-nextjs-plain colored",
  next: "devicon-nextjs-plain colored",
  vue: "devicon-vuejs-plain colored",
  vuejs: "devicon-vuejs-plain colored",
  angular: "devicon-angular-plain colored",
  angularjs: "devicon-angular-plain colored",
  svelte: "devicon-svelte-plain colored",
  redux: "devicon-redux-original colored",
  gatsby: "devicon-gatsby-plain colored",

  // Programming Languages
  typescript: "devicon-typescript-plain colored",
  ts: "devicon-typescript-plain colored",
  javascript: "devicon-javascript-plain colored",
  js: "devicon-javascript-plain colored",
  python: "devicon-python-plain colored",
  java: "devicon-java-plain colored",
  c: "devicon-c-plain colored",
  cpp: "devicon-cplusplus-plain colored",
  cplusplus: "devicon-cplusplus-plain colored",
  csharp: "devicon-csharp-plain colored",
  cs: "devicon-csharp-plain colored",
  go: "devicon-go-original-wordmark colored",
  golang: "devicon-go-original-wordmark colored",
  rust: "devicon-rust-plain colored",
  php: "devicon-php-plain colored",
  ruby: "devicon-ruby-plain colored",
  swift: "devicon-swift-plain colored",
  kotlin: "devicon-kotlin-plain colored",

  // Markup, Styling & UI Libraries
  html: "devicon-html5-plain colored",
  html5: "devicon-html5-plain colored",
  css: "devicon-css3-plain colored",
  css3: "devicon-css3-plain colored",
  sass: "devicon-sass-original colored",
  scss: "devicon-sass-original colored",
  tailwindcss: "devicon-tailwindcss-plain colored",
  tailwind: "devicon-tailwindcss-plain colored",
  bootstrap: "devicon-bootstrap-plain colored",
  materialui: "devicon-materialui-plain colored",
  mui: "devicon-materialui-plain colored",

  // Backend Frameworks & Runtimes
  nodejs: "devicon-nodejs-plain colored",
  node: "devicon-nodejs-plain colored",
  express: "devicon-express-original colored",
  expressjs: "devicon-express-original colored",
  nestjs: "devicon-nestjs-plain colored",
  django: "devicon-django-plain colored",
  fastapi: "devicon-fastapi-plain colored",
  flask: "devicon-flask-original colored",
  spring: "devicon-spring-plain colored",
  springboot: "devicon-spring-plain colored",
  graphql: "devicon-graphql-plain colored",

  // Databases & ORMs
  mongodb: "devicon-mongodb-plain colored",
  mongo: "devicon-mongodb-plain colored",
  postgresql: "devicon-postgresql-plain colored",
  postgres: "devicon-postgresql-plain colored",
  mysql: "devicon-mysql-plain colored",
  redis: "devicon-redis-plain colored",
  firebase: "devicon-firebase-plain colored",
  sqlite: "devicon-sqlite-plain colored",

  // DevOps, Cloud & Tools
  docker: "devicon-docker-plain colored",
  kubernetes: "devicon-kubernetes-plain colored",
  k8s: "devicon-kubernetes-plain colored",
  aws: "devicon-amazonwebservices-original colored",
  amazonwebservices: "devicon-amazonwebservices-original colored",
  gcp: "devicon-googlecloud-plain colored",
  googlecloud: "devicon-googlecloud-plain colored",
  azure: "devicon-azure-plain colored",
  git: "devicon-git-plain colored",
  github: "devicon-github-original colored",
  gitlab: "devicon-gitlab-plain colored",
  linux: "devicon-linux-plain colored",
  bash: "devicon-bash-plain colored",
  webpack: "devicon-webpack-plain colored",
  vite: "devicon-vite-plain colored",
};
